name: CI workflow
on:
  push:
    branches: ci-cd-final-project
  pull_request:
    branches: ci-cd-final-project
jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.9-slim
    steps:
      - name: Install dependencies
        uses: actions/checkout@v3
      - name: Checkout
        run: |
        python -m pip install --upgrade pip
        {pip install -r requirements.txt}
